//! Integration tests for the full JSON -> `SuitManifest` -> CBOR pipeline.
//!
//! These exist because the `cddl` crate (the obvious off-the-shelf validator) has confirmed
//! bugs against real SUIT CDDL (see `docs/cddl-crate-map-groupname-bug.md`) and cannot be
//! trusted as a conformance oracle. Instead:
//!
//! - `golden_*` tests freeze this crate's own output for each `examples/*.json` fixture the
//!   first time it is manually verified spec-conformant (e.g. via an independent CBOR
//!   decoder), then fail loudly on any future *unintentional* wire-format change. Golden
//!   fixtures live in `tests/golden/*.hex`; regenerate with `UPDATE_GOLDEN=1 cargo test`
//!   only after confirming the new bytes are still correct.
//! - `structural_*` tests decode the output independently (via `ciborium::Value`, not this
//!   crate's own `Serialize` impls) and assert the shape CDDL requires, without depending on
//!   a full external schema engine.
//! - `shorthand_and_standard_form_are_byte_identical` locks in that parse.rs's
//!   `suit-condition-version` convenience expansion produces exactly the CBOR a
//!   human-authored, spec-literal `suit-directive-try-each` would.

use std::fs::{self, File};
use std::io::BufReader;

use ciborium::Value;
use sha256::Sha256Digest;
use taylor::encode::{encode_envelope, encode_manifest};
use taylor::manifest::{SuitAuthentication, SuitDigest, SuitEnvelope};
use taylor::parse::parse;

/// Mirrors `main.rs`'s unsigned (digest-only) envelope construction.
fn build_envelope_cbor(json_path: &str) -> Vec<u8> {
    let mut reader = BufReader::new(File::open(json_path).unwrap_or_else(|e| {
        panic!("failed to open fixture {json_path}: {e}");
    }));
    let manifest = parse(&mut reader).unwrap_or_else(|e| {
        panic!("failed to parse fixture {json_path}: {e}");
    });

    let manifest_cbor = encode_manifest(&manifest);
    let digest_hex = manifest_cbor.digest();
    let digest = hex::decode(&digest_hex).expect("sha256 digest hex must be valid");

    let envelope = SuitEnvelope {
        auth_block: SuitAuthentication {
            digest: SuitDigest {
                algorithm: "sha256".to_owned(),
                digest,
            },
            auth_blocks: Vec::new(),
        },
        manifest,
    };
    encode_envelope(&envelope)
}

fn golden_path(name: &str) -> String {
    format!("tests/golden/{name}.hex")
}

/// Compares `actual` against the checked-in golden fixture for `name`, or (only when
/// `UPDATE_GOLDEN=1` is set) overwrites it - an intentional, explicit escape hatch so
/// fixtures are never silently regenerated by a routine `cargo test` run.
fn assert_matches_golden(name: &str, actual: &[u8]) {
    let path = golden_path(name);
    let actual_hex = hex::encode(actual);

    if std::env::var_os("UPDATE_GOLDEN").is_some() {
        fs::write(&path, &actual_hex).unwrap_or_else(|e| panic!("failed to write {path}: {e}"));
        return;
    }

    let expected_hex = fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "missing golden fixture {path}: {e}\n\
             run with UPDATE_GOLDEN=1 after manually verifying the new output is spec-conformant"
        )
    });
    assert_eq!(
        actual_hex,
        expected_hex.trim(),
        "encoded output for {name} no longer matches tests/golden/{name}.hex.\n\
         If this change is intentional and spec-conformant, rerun with UPDATE_GOLDEN=1."
    );
}

macro_rules! golden_test {
    ($test_name:ident, $fixture:literal) => {
        #[test]
        fn $test_name() {
            let cbor = build_envelope_cbor(concat!("examples/", $fixture, ".json"));
            assert_matches_golden($fixture, &cbor);
        }
    };
}

golden_test!(golden_manifest_handler, "manifest-handler");
golden_test!(golden_manifest_handler_version, "manifest-handler-version");
golden_test!(
    golden_manifest_handler_standard,
    "manifest-handler-standard"
);
golden_test!(golden_test_json, "test");
golden_test!(golden_prep_manifest, "prep-manifest");

/// Decodes with `ciborium::Value` (independent of this crate's own `Serialize` impls) and
/// checks the structural invariants `SUIT_Envelope`/`SUIT_Manifest` require, standing in for
/// the CDDL conformance checks a working `cddl` validator would otherwise provide.
fn decode_envelope(cbor: &[u8]) -> (u64, Value) {
    assert_eq!(&cbor[0..2], &[0xD8, 0x6B], "envelope must be tagged 107");
    let value: Value = ciborium::de::from_reader(&cbor[2..]).expect("envelope must be valid CBOR");
    let Value::Map(entries) = &value else {
        panic!("SUIT_Envelope must be a CBOR map, got {value:?}");
    };
    // suit-authentication-wrapper (2) and suit-manifest (3) are the only required keys.
    let keys: Vec<i128> = entries
        .iter()
        .map(|(k, _)| {
            k.as_integer()
                .expect("envelope keys must be integers")
                .into()
        })
        .collect();
    assert!(
        keys.contains(&2),
        "envelope missing suit-authentication-wrapper (key 2)"
    );
    assert!(keys.contains(&3), "envelope missing suit-manifest (key 3)");
    (keys.len() as u64, value)
}

fn map_get<'a>(value: &'a Value, key: i128) -> Option<&'a Value> {
    value
        .as_map()?
        .iter()
        .find(|(k, _)| k.as_integer().map(Into::into) == Some(key))
        .map(|(_, v)| v)
}

#[test]
fn structural_envelope_and_manifest_shape() {
    let cbor = build_envelope_cbor("examples/manifest-handler.json");
    let (_, envelope) = decode_envelope(&cbor);

    let manifest_bstr = map_get(&envelope, 3)
        .unwrap()
        .as_bytes()
        .expect("suit-manifest must be a bstr");
    let manifest: Value = ciborium::de::from_reader(manifest_bstr.as_slice()).unwrap();

    // suit-manifest-version (1), suit-manifest-sequence-number (2), suit-common (3) are
    // mandatory; suit-install (20) is present because manifest-handler.json defines it.
    for required_key in [1i128, 2, 3, 20] {
        assert!(
            map_get(&manifest, required_key).is_some(),
            "SUIT_Manifest missing required key {required_key}"
        );
    }

    let common_bstr = map_get(&manifest, 3).unwrap().as_bytes().unwrap();
    let common: Value = ciborium::de::from_reader(common_bstr.as_slice()).unwrap();
    // suit-common-components (2) and suit-shared-sequence (4), per SUIT_Common.
    assert!(
        map_get(&common, 2).is_some(),
        "SUIT_Common missing suit-components (key 2)"
    );
    assert!(
        map_get(&common, 4).is_some(),
        "SUIT_Common missing suit-shared-sequence (key 4)"
    );
}

/// A `suit-directive-try-each` branch's argument must be an ARRAY of bstr-wrapped command
/// sequences (one per branch), never a bare command sequence - the mistake the shorthand's
/// hand-written equivalent is easy to make.
#[test]
fn structural_try_each_branches_are_bstr_wrapped_array_elements() {
    let cbor = build_envelope_cbor("examples/manifest-handler-standard.json");
    let (_, envelope) = decode_envelope(&cbor);
    let manifest_bstr = map_get(&envelope, 3).unwrap().as_bytes().unwrap();
    let manifest: Value = ciborium::de::from_reader(manifest_bstr.as_slice()).unwrap();
    let common_bstr = map_get(&manifest, 3).unwrap().as_bytes().unwrap();
    let common: Value = ciborium::de::from_reader(common_bstr.as_slice()).unwrap();
    let shared_bstr = map_get(&common, 4).unwrap().as_bytes().unwrap();
    let shared: Value = ciborium::de::from_reader(shared_bstr.as_slice()).unwrap();

    let flat = shared
        .as_array()
        .expect("shared sequence must be a flat array");
    // Find the try-each command (code 15) among the (code, arg) pairs.
    let mut found = false;
    let mut i = 0;
    while i < flat.len() {
        if flat[i].as_integer() == Some(15.into()) {
            found = true;
            let branches = flat[i + 1]
                .as_array()
                .expect("try-each argument must be an array");
            assert_eq!(
                branches.len(),
                3,
                "expected one branch per acceptable version"
            );
            for branch in branches {
                assert!(
                    branch.as_bytes().is_some(),
                    "each branch must be a bstr, not inlined"
                );
            }
        }
        i += 2;
    }
    assert!(
        found,
        "expected a suit-directive-try-each (code 15) in the shared sequence"
    );
}

/// `parse()` must reject malformed/unknown input with `Err`, not panic, for the cases it
/// already documents as returning `Error` (unknown command keys).
#[test]
fn unsupported_command_key_is_rejected_not_ignored() {
    let dir = std::env::temp_dir();
    let path = dir.join("taylor_test_unknown_command.json");
    fs::write(
        &path,
        r#"{
            "version": 1,
            "sequence-number": 1,
            "suit-common": { "suit-components": [["00"]], "suit-shared-sequence": [] },
            "sequence": { "payload-installation": [ {"suit-directive-nonexistent": 1} ] }
        }"#,
    )
    .unwrap();

    let mut reader = BufReader::new(File::open(&path).unwrap());
    let result = parse(&mut reader);
    fs::remove_file(&path).ok();

    assert!(
        result.is_err(),
        "unknown command keys must not be silently accepted"
    );
}
